name: task
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  modal_progress_hud: ^0.1.3
  awesome_dialog: ^1.1.3
  cupertino_icons: ^0.1.3
  google_fonts: ^0.2.0

  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7

  google_sign_in: ^4.1.1

  validators: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - images/a_dot_ham.jpeg

  fonts:
    - family: Abel
    - family: Schyler
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
        - asset: fonts/Schyler-Regular.ttf
        - asset: fonts/Schyler-Italic.ttf
          style: italic
        - asset: fonts/TrajanPro.ttf
        - asset: fonts/TrajanPro_Bold.ttf
          weight: 700